### ISSUE TITLE
ER: Change format of command line parameters

### ISSUE THREAD

**Issue by paolobellardone** [loiclefevre/dragon#15]
I suggest to use a more standard approach in command.line parameters, such as the one used by oci-cli and other tools.
For example, instead of using:
./dragon -load -db <database name>
I would use:
./dragon load -db <database name>
where "load" is the command and "-db <database name>" is the option of the command.
It would be clearer to understand and easier to maintain.

**Comment by loiclefevre** [comment]
The purpose of CLI flags here is to add additional and optional steps for each run of dragon.
Hence by default, you'll ask for the creation of the database...
In case you *also* want to load data from local file then you can add the -load option on the command line...

Later, it will be the same approach with other flags.
