### ISSUE TITLE
ER: First run interview to create a config file

### ISSUE THREAD

**Issue by paolobellardone** [loiclefevre/dragon#16]
To create the config.txt file it would be useful to have an interview to gather all the details needed to connect to the OCI tenancy.
For example, when a user runs dragon for the first time and it does not find the config.txt file, the program could start asking questions to get all the details of user's OCI tenancy.

**Comment by loiclefevre** [comment]
Next release will display the config template in case no config.txt file is found or in case of config.txt file configuration error.
