### ISSUE TITLE
ER: Use an OS default location for config file

### ISSUE THREAD

**Issue by paolobellardone** [loiclefevre/dragon#17]
I suggest to use a standard location for each OS to store the config.txt file because not all OSs allow to write the directory where the executable is stored.
For example in Linux or ain any Un*x-based system, if I put the dragon executable in /usr/bin I will not be able to write in it unless I change the default permissions for directory.
Moreover it is better to keep config separated from binaries and use the default user directory to store the configuration file (i.e. in /home/<username/.config or similar)

**Comment by loiclefevre** [comment]
According to my tests, you can copy the native executable into your /usr/sbin, cd to a directory where you can write, create a config.txt file and run dragon from here.

Isn't it the case for you?

**Comment by paolobellardone** [comment]
As far as you can sudo, you can do almost everything with your filesystem. Having said that the approach I suggested is to have a single config file, placed in a well known location and then leverage profiles to manage different cloud tenancy configurations.
In my experience the approach of putting a file inside any directory could bring to a proliferation of config files which would be had to maintain and be aware of.

**Comment by loiclefevre** [comment]
The approach mimics the one from the Node.js world such as using **package.json**

In the case a global configuration is required then yes that will be the approach taken... but not for the moment.
