### ISSUE TITLE
ER: rename config.txt to be less generic

### ISSUE THREAD

**Issue by paolobellardone** [loiclefevre/dragon#20]
As the DRAGON config file, config.txt, will be stored in the project directory of the application wouldn’t it be better to give it a less generic name, such as config.dragon or dragon.config so that it is easily identified among others (config) files.
This would also enable to integrate the DRAGON config management with the IDE, for example developing an extension to visually manage the configuration.

**Comment by loiclefevre** [comment]
Starting from v1.0.3, the configuration file will be named:

**dragon.config**
