### ISSUE TITLE
Dragon x Linux version dragon-linux-x86_64-1.0.2 error with "Object storage configuration"

### ISSUE THREAD

**Issue by davideburdese** [loiclefevre/dragon#21]
./dragon-linux-x86_64-1.0.2  
DRAGON Stack manager v1.0.2

> Command line parameters ................................................... ok
> Oracle Cloud Infrastructure configuration ................................. ok
> Database creation ................................................. ok [4m 0s]
> Database wallet download ..................................... ok [dragon.zip]
> Database configuration .................................................... ok
> Object storage configuration .......................... creating dragon bucket
================================================================================
Unhandled exception:
javax.ws.rs.ProcessingException: Error reading entity from input stream.
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:889)
        at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)

**Comment by loiclefevre** [comment]
Hello Davide, 
Is it reproducible at will?
Is the Java stacktrace stopping after these 3 lines?
Thanks

**Comment by davideburdese** [comment]
Yes, at least with my free account
Thanks

**Comment by loiclefevre** [comment]
Related to GraalVM native image generation.

**Comment by loiclefevre** [comment]
fixed in v2.0.0
