### ISSUE TITLE
ER: Syntax checking for dragon.config

### ISSUE THREAD

**Issue by paolobellardone** [loiclefevre/dragon#25]
It would be more than useful to have a syntax checking pass of the dragon.config before start provisioning the database in order to verify that all the parameters in the file are valid.
Even if only one is not recognized it should stop and emit and error message.

**Comment by loiclefevre** [comment]
check fingerprint length

**Comment by loiclefevre** [comment]
It's not possible today to programmatically list all properties from the configuration file (limitations of OCI SDK for Java).

**Comment by loiclefevre** [comment]
@paolobellardone, if you've got examples of errors you did while filling up the configuration file, please comment so that I can just the controls...

**Comment by loiclefevre** [comment]
I found a way by redeveloping a configuration file loader that exposes all the parameter names.
