### ISSUE TITLE
Add Spring Boot based frontend stack

### ISSUE THREAD

**Issue by loiclefevre** [loiclefevre/dragon#26]

**Comment by loiclefevre** [comment]
Using https://start.spring.io/

**Comment by bnasslahsen** [comment]
Hi @loiclefevre, 

  In addition to the SODA API, I propose we add a spring-data module for Oracle JSON Database, that simplifies/abstracts the usage of SODA for spring-boot projects.

 Ideally, the developer should only handle interfaces like `CrudRepository` in a large majority of cases.

**Comment by loiclefevre** [comment]
Added a way to create a micro-service based stack.
