### ISSUE TITLE
./dragon-linux-x86_64-2.0.0 java.lang.RuntimeException: REST SODA Service could not create collection dragon

### ISSUE THREAD

**Issue by davideburdese** [loiclefevre/dragon#27]
./dragon-linux-x86_64-2.0.0
DRAGON Stack manager v2.0.0
> Command line parameters ................................................... ok
> Oracle Cloud Infrastructure configuration ................................. ok
> Database creation ................................................. ok [1m 4s]
> Database wallet download ..................................... ok [dragon.zip]
> Database configuration ........................... creating dragon collections
================================================================================
Unhandled exception:
java.lang.RuntimeException: REST SODA Service could not create collection dragon
        at com.oracle.dragon.util.ADBRESTService.createSODACollection(ADBRESTService.java:123)

Manuela Mustatea has the same error.

I'm running on Frankfurt region while Manuela is running on London. 

Thanks

**Comment by loiclefevre** [comment]
ORDS 20.3 is being deployed... would that be related?

**Comment by davideburdese** [comment]
Three test ....

--------------------------------------------------------------------------------------------------------
**without database_collections parameter**

./dragon-linux-x86_64-2.0.0 
DRAGON Stack manager v2.0.0

> Command line parameters ................................................... ok
> Oracle Cloud Infrastructure configuration ................................. ok
> Database creation ................................................ ok [1m 57s]
> Database wallet download ..................................... ok [dragon.zip]
> Database configuration .................................................... ok  
> Object storage configuration .............................................. ko
The object storage credential for the database couldn't be configured.
duration: 2m 15s


**User dragon has NOT been created
Bucket dragon has been created**
--------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------
**with database_collections parameter as follow**
database_collections=testcoll

./dragon-linux-x86_64-2.0.0 
DRAGON Stack manager v2.0.0

> Command line parameters ................................................... ok
> Oracle Cloud Infrastructure configuration ................................. ok
> Database creation ................................................. ok [1m 4s]
> Database wallet download ..................................... ok [dragon.zip]
> Database configuration ........................... creating dragon collections
================================================================================
Unhandled exception:
java.lang.RuntimeException: REST SODA Service could not create collection dragon
        at com.oracle.dragon.util.ADBRESTService.createSODACollection(ADBRESTService.java:123)
        at com.oracle.dragon.util.DSSession.createCollections(DSSession.java:840)
--------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------
**with -db option**

./dragon-linux-x86_64-2.0.0 -db testdrag
DRAGON Stack manager v2.0.0

> Command line parameters ................................................... ok
> Oracle Cloud Infrastructure configuration ................................. ok
> Database creation ................................................. ok [2m 4s]
> Database wallet download ................................... ok [testdrag.zip]
> Database configuration .................................................... ok
> Object storage configuration .............................................. ko
The object storage credential for the database couldn't be configured.
duration: 2m 24s

**User dragon has NOT been created
Bucket dragon has been created**
--------------------------------------------------------------------------------------------------------

**Comment by paolobellardone** [comment]
I have the same issue running dragon on MacOS Catalina

**Comment by loiclefevre** [comment]
Ok, thanks Paolo for your help on this. Several cascading issues here:

1. the user wasn't created properly because the password wasn't enclosed with double quotes
2. but the ORDS call was returning a 200 HTTP code which doesn't mean everything went well including the Database commands
3. and then DRAGON did continue with collections creation but the user didn't exist blah blah etc...

So expect a quick patch this afternoon...

**Comment by loiclefevre** [comment]
Will be fixed in 2.0.1
