### ISSUE TITLE
Show -help if there is a typo or unrecognized parameter 

### ISSUE THREAD

**Issue by tmcginn** [loiclefevre/dragon#30]
Currently, the code executes the stack if a parameter is passed in that the code doesn't recognize. For example:

./dragon-linux-x86_64-2.0.0 -config-temaplate

Default behavior should be to show -help

**Comment by loiclefevre** [comment]
In the case the parameter is not a standard one then starting with 2.0.1 (soon to be released), usage will be shown.

Running the command without any parameter will create the stack (at least the database).
