### ISSUE TITLE
destroy by database name 

### ISSUE THREAD

**Issue by mmanu-gh** [loiclefevre/dragon#33]
add following capability
 ./dragon-linux-x86_64-2.0.1 -destroy < database name >

**Comment by loiclefevre** [comment]
specifying the -db doesn't work?

**Comment by mmanu-gh** [comment]
I want to specify a name:
./dragon-linux-x86_64-2.0.1 -destroy **test2**

**Comment by loiclefevre** [comment]
could you please try 

./dragon-linux-x86_64-2.0.1 -destroy -db test2

**Comment by mmanu-gh** [comment]
Worked like: 
./dragon-linux-x86_64-2.0.1 -destroy -db test2
I didn't combined the params.

**Comment by loiclefevre** [comment]
perfect

**Comment by mmanu-gh** [comment]
From the help:
-db <database name>           to denote the database name to create
 Would be useful to add:   to denote the database name to create/destroy

**Comment by loiclefevre** [comment]
You are right
