### ISSUE TITLE
Enable DRCP for Always Free (?)

### ISSUE THREAD

**Issue by loiclefevre** [loiclefevre/dragon#44]

**Comment by loiclefevre** [comment]
https://docs.oracle.com/en/cloud/paas/atp-cloud/atpug/connect-drcp.html#GUID-E1337EC6-4A78-4199-84F0-A2739055F3FA

**Comment by cjbj** [comment]
Why?

**Comment by loiclefevre** [comment]
20 sessions max for atp free tier

**Comment by cjbj** [comment]
What do you mean 'enable?'.  DRCP is great for high end apps, but do you really want to make users think they always need it?

**Comment by loiclefevre** [comment]
http://oracle.ninja/oracle-cloud-ora-00018-maximum-number-of-sessions-exceeded-use-drcp/

**Comment by loiclefevre** [comment]
Review spring boot petclinic stack to ensure we don't use more than 20 sessions

**Comment by loiclefevre** [comment]
Closing for now, maybe reopen in case of...
