### ISSUE TITLE
Add a "latest" softlink that points to the current latest version of the stack

### ISSUE THREAD

**Issue by tmcginn** [loiclefevre/dragon#50]
This way, the wget command will always pull the latest:

wget https://github.com/loiclefevre/dragon/releases/download/v2.0.0/dragon-linux-86_64-latest

**Comment by tmcginn** [comment]
maybe simplified:
wget https://github.com/loiclefevre/dragon/releases/download/linux-86_64/latest

**Comment by loiclefevre** [comment]
We can't do that because the -upgrade command would then fail because it can't overwrite the currently executing binary.
