### ISSUE TITLE
ER: Add Oracle Jet starter front end

### ISSUE THREAD

**Issue by paolobellardone** [loiclefevre/dragon#52]
Add a starter project for Oracle Jet, https://www.oracle.com/webfolder/technetwork/jet/index.html?ojr=getstarted

**Comment by loiclefevre** [comment]
@paolobellardone, the way it works... create a minimal, fully running project, then share it with me for integration :)

**Comment by paolobellardone** [comment]
Exploring a couple of demos that I can adapt to be used with DRAGON stack

**Comment by paolobellardone** [comment]
I developed the starter app and a more structured one.
